name: _error
timestamp: 1693114924
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1630204279
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-4734: Aside
    position-position-3949: Sidebar
  content:
    system-content-1587: 'Page Content'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
  messages:
    system-messages-9466: 'System Messages'
  logo:
    logo-7395: 'Logo / Image'
    logo-9905: Branding
  menu:
    menu-6613: Menu
  widget:
    position-widget-8840: Widget
    position-widget-9401: 'Company menu'
    position-widget-8071: 'Legal menu'
    position-widget-3861: 'Business menu'
    position-widget-3157: 'Explore menu'
  custom:
    custom-3424: 'Inner Pages Newsletter Widget'
    custom-9951: 'Follow Us'
  copyright:
    copyright-9970: Copyright
  totop:
    totop-9230: 'To Top'
inherit:
  default:
    navigation: navigation
    footer: footer
    system-messages-9466: system-messages-7972
    logo-7395: logo-9608
    menu-6613: menu-6409
    position-widget-8840: position-widget-6909
    custom-3424: custom-6599
    position-widget-9401: position-widget-4832
    position-widget-8071: position-widget-3539
    position-widget-3861: position-widget-3496
    position-widget-3157: position-widget-5747
    custom-9951: custom-1968
    logo-9905: logo-9323
    copyright-9970: copyright-1736
    totop-9230: totop-8670
